# Basic Site Settings
locale                   : "en-US"
title                    : "Mahfuzur Rahman Chowdhury"
title_separator          : "-"
name                     : &name "Mahfuzur Rahman Chowdhury"
#description              : &description ""
url                      : https://anik-3.github.io
baseurl                  : "portfolio"
repository               : "academicpages/academicpages.github.io"

author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Mahfuzur Rahman Chowdhury"
  pronouns         : "he/him"  
  #bio              : ""
  location         : "Sylhet, Bangladesh"
  employer         : "Red Brick University"
  uri              : # URL
  #email            : "" 

  # Academic websites
  github           : "anik-3" 

  # Social media
  facebook         : # Username
  instagram        : # Username
  linkedin         : # Username
  steam            : # Username
  telegram         : # URL
  twitter          : # Username for X / Twitter
  youtube          : # Username

  # Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'



# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # change to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml
